POST http://localhost:3003/estudante
Content-Type: application/json

{ 
"nome": "Gabriel", 
"email": "gabriel@labenu.com", 
"data_nasc": "2020-01-01", 
"turma_id": "014"
}

###

GET http://localhost:3003/estudante

###

PUT http://localhost:3003/estudante
Content-Type: application/json

{
    "aluno_id": "1662732881038",
    "turma_id": "011"
}

###

POST http://localhost:3003/criar-turma
Content-Type: application/json

{
    "nome":"Silva"
}

###

GET http://localhost:3003/selecionar-turmas

###

Put http://localhost:3003/mudanca-modulo
Content-Type: application/json

{
    {
    "idTurma":"014",
    "modulo":"2"
}

}